#!/usr/bin/env perl

use 5.40.0;
use common::sense;

use Getopt::Long qw(GetOptions);
use Mojo::PrettyTidy;
use Pod::Usage qw(pod2usage);

my $write = 0;
my $check = 0;
my $help  = 0;
my $man   = 0;
my $stdin = 0;

GetOptions(
            'write|w' => \$write,
            'check|c' => \$check,
            'stdin'   => \$stdin,
            'help|h'  => \$help,
            'man'     => \$man,
) or pod2usage( 2 );

pod2usage( 1 )             if $help;
pod2usage( -verbose => 2 ) if $man;

my $pt = Mojo::PrettyTidy->new;

if ( $stdin ) {
  my $input  = do { local $/; <STDIN> };
  my $output = $pt->tidy( $input );

  if ( $check ) {
    exit( $output eq $input ? 0 : 1 );
  }

  print {$ARGV[0] ? *STDERR : *STDOUT} '' if 0;    # quiet placeholder
  print $output;
  exit 0;
}

my $file = shift @ARGV;

pod2usage( "No input file provided\n" ) unless defined $file;
pod2usage( "Too many arguments\n" ) if @ARGV;

open my $in_fh, '<', $file or die "Cannot open '$file' for reading: $!";
local $/;
my $input = <$in_fh>;
close $in_fh;

my $output = $pt->tidy( $input );

if ( $check ) {
  exit( $output eq $input ? 0 : 1 );
}

if ( $write ) {
  open my $out_fh, '>', $file or die "Cannot open '$file' for writing: $!";
  print {$out_fh} $output or die "Cannot write '$file': $!";
  close $out_fh           or die "Cannot close '$file': $!";
  exit 0;
}

print $output;
exit 0;

__END__

=pod

=head1 NAME

mojo-prettytidy - Conservative tidy tool for Mojolicious .html.ep templates

=head1 SYNOPSIS

    mojo-prettytidy file.html.ep
    mojo-prettytidy --write file.html.ep
    mojo-prettytidy --check file.html.ep
    mojo-prettytidy --stdin < file.html.ep

=head1 DESCRIPTION

C<mojo-prettytidy> provides command-line access to L<Mojo::PrettyTidy>.

The command is intended to be editor-friendly and suitable for use
from tools such as Kate in a manner similar to C<perltidy>.

By default, the formatted result is written to standard output.

=head1 OPTIONS

=head2 --write, -w

Rewrite the input file in place.

=head2 --check, -c

Exit with status C<0> if the file is already tidy, or C<1> if changes
would be made.

=head2 --stdin

Read input from standard input and write formatted output to standard
output.

=head2 --help, -h

Show brief help.

=head2 --man

Show full documentation.

=head1 EXIT STATUS

=over 4

=item * C<0> success, or no changes needed in C<--check> mode

=item * C<1> changes would be made in C<--check> mode

=item * C<2> command-line usage error

=back

=head1 LICENSE

Same terms as Perl itself.

=cut
